[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "intra"
version = "1.0.0"
dependencies = [
	"pyyaml==6.0.1",
	"requests==2.25.1",
	"tqdm==4.56.0",
	"pygments==2.9.0",
]
requires-python = ">=3.8"
